version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 20
    commands:
        - echo Installing source NPM dependencies...
        - npm install
  pre_build:
    commands:
        - echo Running tests...
        - npm run test:headless
  build:
    commands:
        - echo Build started 
        - npm run build:prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes